Allow shell meta-character problems in SNMP vars
infrawatch/prometheus-webhook-snmp pull request #16
Opened 2023-02-27 22:11 UTC by csibbitt

While reviewing another patch I noticed that the existing code likely could not support a strong community string, so I adjusted all the params for consistency.

2023-02-27 22:11 UTC, csibbitt commented
Both the asserted bug and the proposed fix are untested, I just saw this and wanted to make a note.

2023-02-28 13:45 UTC, leifmadsen commented
I'll give this a shot today and make sure everything works as intended.

2023-03-01 16:11 UTC, leifmadsen commented
```
$  git diff master
$  oc get buildconfigs
NAME                         TYPE     FROM         LATEST
prometheus-webhook-snmp      Docker   Dockerfile   2
service-telemetry-operator   Docker   Dockerfile   2
sg-bridge                    Docker   Dockerfile   2
sg-core                      Docker   Dockerfile   2
smart-gateway-operator       Docker   Dockerfile   2

$  oc start-build prometheus-webhook-snmp --wait --from-dir .
Uploading directory "." as binary input for the build ...
..
Uploading finished
build.build.openshift.io/prometheus-webhook-snmp-3 started

oc get pod default-snmp-webhook-7d9f566599-zlrtk -oyaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.130.0.154"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.130.0.154"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted
  creationTimestamp: "2023-02-22T22:33:43Z"
  generateName: default-snmp-webhook-7d9f566599-
  labels:
    app: default-snmp-webhook
    pod-template-hash: 7d9f566599
  name: default-snmp-webhook-7d9f566599-zlrtk
  namespace: service-telemetry
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: default-snmp-webhook-7d9f566599
    uid: 13034eb1-1a7b-47f4-977a-63ea51250095
  resourceVersion: "30566526"
  uid: 59db243b-b7e4-4f8e-958e-74b21052787d
spec:
  containers:
  - env:
    - name: SNMP_COMMUNITY
      value: public
    - name: SNMP_RETRIES
      value: "5"
    - name: SNMP_HOST
      value: snmptrapd
    - name: SNMP_PORT
      value: "6200"
    - name: SNMP_TIMEOUT
      value: "6200"
    - name: ALERT_OID_LABEL
      value: oid
    - name: TRAP_OID_PREFIX
      value: 1.3.6.1.4.1.50495.15
    - name: TRAP_DEFAULT_OID
      value: 1.3.6.1.4.1.50495.15.1.2.1
    - name: TRAP_DEFAULT_SEVERITY
    image: image-registry.openshift-image-registry.svc:5000/service-telemetry/prometheus-webhook-snmp:latest
    imagePullPolicy: Always
    name: prometheus-webhook-snmp
    ports:
    - containerPort: 9099
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000690000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vx5ls
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: default-dockercfg-w9gwn
  nodeName: madsplayground-t8gbz-master-2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000690000
    seLinuxOptions:
      level: s0:c26,c20
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-vx5ls
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-02-22T22:33:43Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-02-22T22:33:46Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-02-22T22:33:46Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-02-22T22:33:43Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://c295171e1aeaa4117280a6d9155e30a4d5cfe872359d19830bcfb0998bc961a7
    image: image-registry.openshift-image-registry.svc:5000/service-telemetry/prometheus-webhook-snmp:latest
    imageID: image-registry.openshift-image-registry.svc:5000/service-telemetry/prometheus-webhook-snmp@sha256:3fb3c9a975421d5edbc8e57767aa0019c9898e91073696fc7ac84277fed00764
    lastState: {}
    name: prometheus-webhook-snmp
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-02-22T22:33:45Z"
  hostIP: 192.168.128.96
  phase: Running
  podIP: 10.130.0.154
  podIPs:
  - ip: 10.130.0.154
  qosClass: BestEffort
  startTime: "2023-02-22T22:33:43Z"

# checking the sha256 hash of the container image and making note

oc get build prometheus-webhook-snmp-3 -oyaml
apiVersion: build.openshift.io/v1
kind: Build
metadata:
  annotations:
    openshift.io/build-config.name: prometheus-webhook-snmp
    openshift.io/build.number: "3"
    openshift.io/build.pod-name: prometheus-webhook-snmp-3-build
  creationTimestamp: "2023-03-01T15:43:43Z"
  generation: 2
  labels:
    build: prometheus-webhook-snmp
    buildconfig: prometheus-webhook-snmp
    openshift.io/build-config.name: prometheus-webhook-snmp
    openshift.io/build.start-policy: Serial
  name: prometheus-webhook-snmp-3
  namespace: service-telemetry
  ownerReferences:
  - apiVersion: build.openshift.io/v1
    controller: true
    kind: BuildConfig
    name: prometheus-webhook-snmp
    uid: 33fcfdff-d304-4917-b7e5-5d8832849932
  resourceVersion: "34533562"
  uid: 5f76ac21-c021-41dd-9706-d5db463dd453
spec:
  nodeSelector: null
  output:
    pushSecret:
      name: builder-dockercfg-5wm8m
    to:
      kind: ImageStreamTag
      name: prometheus-webhook-snmp:latest
  postCommit: {}
  resources: {}
  revision:
    git:
      author:
        email: csibbitt@redhat.com
        name: Chris Sibbitt
      commit: 8dfb0a328ef68cdf235e0a76bf88e16b0413d76e
      committer:
        email: noreply@github.com
        name: GitHub
      message: Update Dockerfile
    type: Git
  serviceAccount: builder
  source:
    binary: {}
    dockerfile: |
      FROM quay.io/centos/centos:stream8

      RUN INSTALL_PKGS="\
              procps-ng \
              telnet \
              lsof \
              python3 \
              python3-devel \
              gcc \
              " && \
          dnf -y --setopt=tsflags=nodocs --setopt=skip_missing_names_on_install=False install $INSTALL_PKGS && \
          dnf -y clean all

      COPY . /source/app
      WORKDIR /source/app

      RUN alternatives --set python /usr/bin/python3 && \
          python -m pip install --no-cache-dir --upgrade setuptools pip && \
          python -m pip install --no-cache-dir wheel && \
          python -m pip install --no-cache-dir -r requirements-build.txt && \
          python -m pip install --no-cache-dir . && \
          python -m pip freeze

      # Cleanup
      RUN UNINSTALL_PKGS="\
              gcc \
              " && \
          dnf remove -y $UNINSTALL_PKGS && \
          dnf -y clean all

      ENV SNMP_COMMUNITY="public"
      ENV SNMP_PORT=162
      ENV SNMP_HOST="localhost"
      ENV SNMP_RETRIES=5
      ENV SNMP_TIMEOUT=1
      ENV ALERT_OID_LABEL="oid"
      ENV TRAP_OID_PREFIX="1.3.6.1.4.1.50495.15"
      ENV TRAP_DEFAULT_OID="1.3.6.1.4.1.50495.15.1.2.1"
      ENV TRAP_DEFAULT_SEVERITY=""

      EXPOSE 9099

      CMD ["sh", "-c", "/ [...]

2023-03-01 16:11 UTC, leifmadsen requested changes
Failing this for now. Haven't dug into why, but building image like this completes the build, but does not work when starting.

2023-03-01 17:55 UTC, leifmadsen commented on Dockerfile
> +CMD ["sh", "-c", "/usr/local/bin/prometheus-webhook-snmp --debug --snmp-port=\"${SNMP_PORT}\" --snmp-host=\"${SNMP_HOST}\" --snmp-community=\"${SNMP_COMMUNITY}\" --snmp-retries=\"${SNMP_RETRIES}\" --
haha nice find :)

2023-03-01 18:07 UTC, leifmadsen commented
I have verified the latest changes here. I deleted the BuildConfig, imported the latest changes, created a new build, deleted the pod, verified the new pod was using the new build hash, and then updated the `ServiceTelemetry` manifest to have a complex community name.

```
oc logs -f --selector=app=default-snmp-webhook
DEBUG:prometheus_webhook_snmp.utils:Configuration settings: {"debug": true, "snmp_host": "snmptrapd", "snmp_port": 6200, "snmp_community": "chris-breaks_theworld", "snmp_retries": 5, "snmp_timeout": 6200, "alert_oid_label": "oid", "trap_oid_prefix": "1.3.6.1.4.1.50495.15", "trap_default_oid": "1.3.6.1.4.1.50495.15.1.2.1", "trap_default_severity": "", "host": "0.0.0.0", "port": 9099, "metrics": false, "cert": "", "key": ""}
INFO:cherrypy.error:[01/Mar/2023:18:05:14] ENGINE Listening for SIGTERM.
INFO:cherrypy.error:[01/Mar/2023:18:05:14] ENGINE Listening for SIGHUP.
INFO:cherrypy.error:[01/Mar/2023:18:05:14] ENGINE Listening for SIGUSR1.
INFO:cherrypy.error:[01/Mar/2023:18:05:14] ENGINE Bus STARTING
INFO:cherrypy.error:[01/Mar/2023:18:05:14] ENGINE Serving on http://0.0.0.0:9099
INFO:cherrypy.error:[01/Mar/2023:18:05:14] ENGINE Bus STARTED
```

2023-03-01 18:07 UTC, leifmadsen approved these changes

2023-03-01 19:18 UTC, merged